<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TgBotGuide.Application\TgBotGuide.Application.csproj"/>
        <ProjectReference Include="..\TgBotGuide.Infrastructure.Refit\TgBotGuide.Infrastructure.Refit.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.4"/>
    </ItemGroup>

</Project>
